Repository thoth-station/nepthys, pull requests merged in 2019-04, with the labels that each got.

#3 Deploy nepthys on openshift
  Dockerfile
  README.rst
  create_docs.sh
  docker_entrypoint.sh
  openshift/buildconfig-template.yaml
  openshift/cronjob-template.yaml
  openshift/imageStream-template.yaml
  openshift/secret-template.yaml
  playbooks/deprovision.yaml
  playbooks/nepthys-deploy/tasks/main.yaml
  playbooks/provision.yaml
Labels: approved, size/L

#5 Disable colors and spinner in Pipenv
  openshift/cronjob-template.yaml
Labels: approved, size/XS

#7 feature to use google analytics on thoth-station.ninja
  Dockerfile
  _templates/layout.html
  create_docs.sh
Labels: approved, size/S
