Repository thoth-station/nepthys, pull requests merged in 2020-11, with the labels that each got.

#49 include assets based on projects
  create_docs.sh
Labels: size/XS

#51 utilize the workdir aspect in the dockerfile
  Dockerfile
Labels: approved, size/XS

#54 Release of version 0.2.5
  CHANGELOG.md
  thoth/nepthys/__init__.py
Labels: approved, bot, size/XS
