Repository thoth-station/nepthys, pull requests merged in 2020-09, with the labels that each got.

#30 Fix serving static content in sphinx docs
  create_docs.sh
Labels: approved, size/S

#32 Release of version 0.2.0
  CHANGELOG.md
  thoth/nepthys/__init__.py
Labels: approved, bot, size/XS

#34 Fix repo listing
  create_docs.sh
Labels: approved, size/XS

#36 Release of version 0.2.1
  CHANGELOG.md
  thoth/nepthys/__init__.py
Labels: approved, bot, size/XS

#37 Fix commit message on routine docs update
  create_docs.sh
Labels: approved, size/XS

#39 Release of version 0.2.2
  CHANGELOG.md
  thoth/nepthys/__init__.py
Labels: approved, bot, size/XS
